server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mmall
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    database: mysql
    show-sql: true
redis1:
  ip: 127.0.0.1
  port: 6379


#最大连接数
redis:
    max:
      total:  20
      idle: 10
    min:
      idle: 2
    test:
      borrow: true
      return: false

close_order_task_time_hour: 2
#毫秒
locktimeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml